{{- if and .Values.metrics.enabled .Values.service.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "app.namespace" . }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}
      scrapeTimeout: {{ .Values.metrics.scrapeTimeout }}
{{- end }}
